server:
  port: 8090


spring:
  datasource:
    username: root
    password: 52wendyma
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.68.139:3306/shopping?serverTimezone=GMT%2B8
    initialSize: 5
    minIdle: 5
    maxActive: 200
  redis:
    host: 175.24.68.139
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-idle: 25
        min-idle: 10
        max-active: 50
        max-wait: -1
  rabbitmq:
    host: 124.223.27.13
    port: 15672
    username: guest
    password: guest
    virtualHost: /


mybatis-plus:
  #配置mapper扫描
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.shop.entity
  typeEnumsPackage: com.example.shop.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: oracle
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true